name: Lineup Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-lineup-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore posted_lineups.json from cache
        uses: actions/cache@v3
        with:
          path: posted_lineups.json
          key: posted-lineups-key

      - name: Ensure file exists
        run: |
          if [ ! -f posted_lineups.json ]; then
            echo "{}" > posted_lineups.json
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run lineup bot
        run: python lineup_bot.py

