name: Lineup Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-lineup-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache posted_lineups.json
        uses: actions/cache@v3
        with:
          path: posted_lineups.json
          key: posted-cache-lineups-${{ github.ref }}

      - name: Run lineup bot
        run: python lineup_bot.py
