name: News Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download posted_news_ids.json
        uses: actions/download-artifact@v4
        with:
          name: news-cache
        continue-on-error: true

      - name: Create fallback posted_news_ids.json if missing
        run: |
          if [ ! -f posted_news_ids.json ]; then
            echo "[]" > posted_news_ids.json
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run news bot
        run: python news_bot.py

      - name: Upload updated posted_news_ids.json
        uses: actions/upload-artifact@v4
        with:
          name: news-cache
          path: posted_news_ids.json

