name: News Bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore posted_news_ids.json from cache
        uses: actions/cache@v3
        with:
          path: posted_news_ids.json
          key: posted-news-key

      - name: Ensure posted_news_ids.json exists
        run: |
          if [ ! -f posted_news_ids.json ]; then
            echo "[]" > posted_news_ids.json
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run news bot
        run: python news_bot.py

