name: News Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache posted file
        uses: actions/cache@v3
        with:
          path: posted_news_ids.json
          key: posted-cache-news-${{ github.ref }}

      - name: Run news bot
        run: python news_bot.py
